#!/bin/bash

# ~/bin/nanoKontroll
# Define these variables to spec. and you should be good to go

nanoKontrollPath=$HOME/bin/nanoKontroll
kontrollPath=$HOME/bin/kontroll
baseLayer=0
mouseLayer=3
gameLayer=4
gameMouseLayer=5
trackballEV=8
zsaMouseEV=3

lockLayer() {
	[[ -f /tmp/layerLock ]] && rm /tmp/layerLock || touch /tmp/layerLock
}
												# We define and check for the
[[ $1 == "lockLayer" ]] && lockLayer && exit	# lock function first
												
[[ ! -f /tmp/trackballEVtracker ]] && touch /tmp/trackballEVtracker
[[ ! -f /tmp/zsaInputTracker ]] && touch /tmp/zsaInputTracker
						# We're using a tmp file here and for the lock instead
						# of variables to allow the background process and user
						# alias/binds to communicate with the foreground proc.

	# The trackball produces more events than we need, to maximize
	# responsiveness of the layer switching we we run evtest seperately in
	# background processes

{
	evtest /dev/input/event$trackballEV |
	grep "time" |
	while read movement; do
		touch /tmp/trackballEVtracker
	done
} &

{
	evtest /dev/input/event$zsaMouseEV |
	grep "time" |
	while read movement; do
		touch /tmp/zsaMouseEVtracker
	done
} &

while true; do

	if [[ $(( $(date +%s%3N) - $(date -r /tmp/trackballEVtracker +%s%3N) )) -lt 1500 ]] && [[ ! -f /tmp/layerLock ]] ; then

		INITIALLAYER=$(/$kontrollPath status | grep 'layer' | cut -f 3)

		if [[ $INITIALLAYER -eq $baseLayer ]] ; then

			/$kontrollPath set-layer --index $mouseLayer 
			/$kontrollPath set-rgb-all --color ffffff

			while [[ $(( $(date +%s%3N) - $(date -r /tmp/trackballEVtracker +%s%3N) )) -lt 1000 ]] || [[ $(( $(date +%s%3N) - $(date -r /tmp/zsaMouseEVtracker +%s%3N) )) -lt 1000 ]] || [[ -f /tmp/layerLock ]] ; do
				sleep 0.6
			done

			EXITLAYER=$(/$kontrollPath status | grep 'layer' | cut -f 3)

			if [[ $EXITLAYER -ne $mouseLayer ]] ; then

					/$kontrollPath restore-rgb-leds

			else

					/$kontrollPath restore-rgb-leds
					/$kontrollPath set-layer --index $INITIALLAYER

			fi

			sleep 0.45	# This helps ensure the 1.5 IF condition is false 

		elif [[ $INITIALLAYER -eq $gameLayer ]] ; then

			/$kontrollPath set-layer --index $gameMouseLayer 

			while [[ $(( $(date +%s%3N) - $(date -r /tmp/trackballEVtracker +%s%3N) )) -lt 1000 ]] || [[ $(( $(date +%s%3N) - $(date -r /tmp/zsaMouseEVtracker +%s%3N) )) -lt 1000 ]] || [[ -f /tmp/layerLock ]] ; do
				sleep 0.6
			done

			EXITLAYER=$(/$kontrollPath status | grep 'layer' | cut -f 3)

			if [[ $EXITLAYER -ne $gameMouseLayer ]] ; then

					/$kontrollPath restore-rgb-leds

			else

					/$kontrollPath restore-rgb-leds
					/$kontrollPath set-layer --index $INITIALLAYER

			fi

			sleep 0.45	# This helps ensure the 1.5 IF condition is false 


		else
			sleep 0.05
		fi

	else
		sleep 0.05
	fi

done

trap 'kill 0' EXIT	#this ensures the background process terminates
